In [1]:
import pandas as pd
from pandas_profiling import ProfileReport

In [3]:
df = pd.read_json('aklamio_challenge.json', lines=True)

In [4]:
df

,event_id,customer_id,fired_at,user_id,event_type,ip,email
0,cc8dac61-f9d0-4bcb-a9aa-602456ee20d4,344,2021-12-31 23:54:21,165,ReferralPageLoad,192.168.176.194,russellsanchez@example.org
1,70652c91-cbfe-41e4-a411-8abbd3d1e355,176,2021-12-31 23:57:56,4242,ReferralPageLoad,172.24.156.222,vjones@example.org
2,52cc1c68-cc56-443a-9bf3-4be09779db32,176,2021-12-31 23:58:19,4837,ReferralPageLoad,172.23.251.141,lberger@example.org
3,59429f69-e083-4818-8d7a-feb565e7a836,344,2021-12-31 23:59:03,1137,ReferralPageLoad,10.179.100.56,martinezwesley@example.net
4,51a6d9aa-f732-426b-97d9-b75cb3c419a0,176,2021-12-31 23:59:07,5257,ReferralPageLoad,172.27.254.121,hking@example.org
...,...,...,...,...,...,...,...
120099,637311aa-2aec-4379-a889-94fae1eaaad5,54,2022-01-09 23:58:56,6213,ReferralPageLoad,172.27.25.178,amy89@example.org
120100,ad7d9048-4d2f-4f37-aae9-c7b9bcc23c6a,176,2022-01-09 23:59:23,1650,ReferralPageLoad,172.18.35.51,dennis78@example.net
120101,3b2a0ab8-89ad-41d2-a6c3-e9f6f96c1d77,32,2022-01-09 23:59:36,9598,ReferralPageLoad,172.23.30.168,wellsthomas@example.net
120102,8bdd5c1d-7217-4965-baf2-f733e7a42f76,344,2022-01-09 23:59:44,7499,ReferralPageLoad,172.17.253.222,rebecca83@example.org
120103,c3c7ceab-0dc2-459d-8819-c23755ffc134,343,2022-01-09 23:59:50,4837,ReferralPageLoad,172.23.251.141,lberger@example.org

In [5]:
df.describe(include='all')

/var/folders/sg/ptjynpp14wq9tkg28kyc2qz00000gp/T/ipykernel_48898/2884002236.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe(include='all')

,event_id,customer_id,fired_at,user_id,event_type,ip,email
count,120104,120104.000000,120104,120104.000000,120104,120104,120104
unique,100000,NaN,111237,NaN,4,99,99
top,a108dadc-b437-470b-bfd1-66f26547de80,NaN,2022-01-05 02:28:46,NaN,ReferralPageLoad,172.31.62.200,ellisjohn@example.net
freq,2,NaN,4,NaN,90007,1337,1337
first,NaN,NaN,2021-12-31 23:54:21,NaN,NaN,NaN,NaN
last,NaN,NaN,2022-01-09 23:59:50,NaN,NaN,NaN,NaN
mean,NaN,139.168238,NaN,4828.595217,NaN,NaN,NaN
std,NaN,128.571228,NaN,2875.818115,NaN,NaN,NaN
min,NaN,12.000000,NaN,130.000000,NaN,NaN,NaN
25%,NaN,29.000000,NaN,2558.000000,NaN,NaN,NaN
50%,NaN,54.000000,NaN,4539.000000,NaN,NaN,NaN
75%,NaN,176.000000,NaN,7565.000000,NaN,NaN,NaN
max,NaN,344.000000,NaN,9979.000000,NaN,NaN,NaN

In [6]:
profile = ProfileReport(df, title="Pandas Profiling Report")

In [7]:
profile.to_file("aklamio_report.html")

Summarize dataset:   0%|          | 0/21 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]